---
abstract: 'Keeping the legacy of Sir Terry Pratchett alive forever'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  File::Spec: '0'
  HTTP::Request::Common: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Plack::Builder: '0'
  Plack::Test: '0'
  Test::More: '0.88'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-Middleware-GNUTerryPratchett
provides:
  Plack::Middleware::GNUTerryPratchett:
    file: lib/Plack/Middleware/GNUTerryPratchett.pm
    version: v0.0.1
requires:
  Plack::Middleware: '0'
  Plack::Util: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Plack-Middleware-GNUTerryPratchett/issues
  homepage: https://github.com/yanick/Plack-Middleware-GNUTerryPratchett
  repository: https://github.com/yanick/Plack-Middleware-GNUTerryPratchett.git
version: 0.0.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
